/*
 * Blog API
 * This is a blog API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dzenancindrak@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Post model module.
 * @module model/Post
 * @version 1.0.0
 */
export class Post {
  /**
   * Constructs a new <code>Post</code>.
   * @alias module:model/Post
   * @class
   * @param id {String} 
   * @param tags {Array.<String>} 
   * @param header {String} 
   * @param content {String} 
   * @param author {String} 
   * @param dateCreated {Date} 
   * @param dateUpdated {Date} 
   */
  constructor(id, tags, header, content, author, dateCreated, dateUpdated) {
    this.id = id;
    this.tags = tags;
    this.header = header;
    this.content = content;
    this.author = author;
    this.dateCreated = dateCreated;
    this.dateUpdated = dateUpdated;
  }

  /**
   * Constructs a <code>Post</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Post} obj Optional instance to populate.
   * @return {module:model/Post} The populated <code>Post</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Post();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('header'))
        obj.header = ApiClient.convertToType(data['header'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'String');
      if (data.hasOwnProperty('dateCreated'))
        obj.dateCreated = ApiClient.convertToType(data['dateCreated'], 'Date');
      if (data.hasOwnProperty('dateUpdated'))
        obj.dateUpdated = ApiClient.convertToType(data['dateUpdated'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Post.prototype.id = undefined;

/**
 * @member {Array.<String>} tags
 */
Post.prototype.tags = undefined;

/**
 * @member {String} header
 */
Post.prototype.header = undefined;

/**
 * @member {String} content
 */
Post.prototype.content = undefined;

/**
 * @member {String} author
 */
Post.prototype.author = undefined;

/**
 * @member {Date} dateCreated
 */
Post.prototype.dateCreated = undefined;

/**
 * @member {Date} dateUpdated
 */
Post.prototype.dateUpdated = undefined;

